### ISSUE TITLE
画布背景色

### ISSUE THREAD

**Issue by xi-qi** [JaimeCheng/vue-esign#1]
无法设置画布得背景色
"vue-esign": "^1.0.5",

**Comment by teresaxiaoming** [comment]
话说，清空画布之后，画布背景色也被清掉了咧？

**Comment by JaimeCheng** [comment]
> 话说，清空画布之后，画布背景色也被清掉了咧？

对的，画布背景色也是你画的的一部分，所以就清掉啦

**Comment by xdw898618984** [comment]
可以重新设置背景颜色

**Comment by JaimeCheng** [comment]
已更新 支持vue3，已增加属性 控制清空画布时是否清空背景色

**Comment by teresaxiaoming** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
