### ISSUE TITLE
最新版本代码有错误

### ISSUE THREAD

**Issue by wrain** [JaimeCheng/vue-esign#14]
![1657166249(1)](https://user-images.githubusercontent.com/7310454/177687498-3cad3526-da0e-433e-ba30-b95b3a816040.png)

**Comment by JaimeCheng** [comment]
你好 请问具体什么问题

**Comment by sjkmuninj** [comment]
webpack 打包的时候报错
![image](https://user-images.githubusercontent.com/7788223/177702096-0ed6fb15-cea8-4332-8f28-cce9a8e21bf8.png)

因为type被重复声明了

**Comment by JaimeCheng** [comment]
更新了 试下

**Comment by JaimeCheng** [comment]
另：属性名 type 改了下名字

**Comment by sjkmuninj** [comment]
> 另：属性名 type 改了下名字

你这样改参数名,之前引用的地方也要调整的;
可以只调整内部变量,不改变参数命名的,
这样其他人不用重新调整代码,只要更新版本即可

**Comment by JaimeCheng** [comment]
这个参数也是今天新加的而已，没差几个小时




Cheng
***@***.***




------------------ 原始邮件 ------------------
发件人: 张三 ***@***.***&gt;
发送时间: 2022年7月7日 14:54
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: JaimeCheng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JaimeCheng/vue-esign] 最新版本代码有错误 (Issue #14)





  
另：属性名 type 改了下名字
  
你这样改参数名,之前引用的地方也要调整的;
 可以只调整内部变量,不改变参数命名的,
 这样其他人不用重新调整代码,只要更新版本即可

**Comment by sjkmuninj** [comment]
> 这个参数也是今天新加的而已，没差几个小时 Cheng ***@***.***
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 张三 ***@***.***&gt; 发送时间: 2022年7月7日 14:54 收件人: JaimeCheng/vue-esign ***@***.***&gt; 抄送: JaimeCheng ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [JaimeCheng/vue-esign] 最新版本代码有错误 (Issue #14) 另：属性名 type 改了下名字 你这样改参数名,之前引用的地方也要调整的; 可以只调整内部变量,不改变参数命名的, 这样其他人不用重新调整代码,只要更新版本即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我是线上部署异常来找答案的...

**Comment by sjkmuninj** [comment]
我是线上部署异常查原因的,不少用户部署都是自动检测版本,如果在这个时间段内有触发更新,就会异常了

**Comment by JaimeCheng** [comment]
这个type属性，就是三个小时前从pr新加的，影响不大，应该还没有用户使用到这个属性，修改下属性名字问题不大

**Comment by JaimeCheng** [comment]
这个type属性，就是三个小时前从pr新加的，影响不大，应该还没有用户使用到这个属性，修改下属性名字问题不大




Cheng
***@***.***




------------------ 原始邮件 ------------------
发件人: 张三 ***@***.***&gt;
发送时间: 2022年7月7日 14:58
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: JaimeCheng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JaimeCheng/vue-esign] 最新版本代码有错误 (Issue #14)





 
我是线上部署异常查原因的,不少用户部署都是自动检测版本,如果在这个时间段内有触发更新,就会异常了
