### ISSUE TITLE
你好，更新到1.1.2版本后，生成的方法会报错找不到 ‘format’

### ISSUE THREAD

**Issue by Snow-wanglong** [JaimeCheng/vue-esign#15]
你好，更新到1.1.2版本后，会报错如下：
Cannot read properties of undefined (reading 'format')

但是我看generate()生成图片的方法，里面可以默认不填内容，是不是可以不对图片进行质量压缩？

**Comment by JaimeCheng** [comment]
已修复 请更新版本

**Comment by JaimeCheng** [comment]
今天更新了一版没测试，疏忽了，马上修复




Cheng
***@***.***




------------------ 原始邮件 ------------------
发件人: Snow-wanglong ***@***.***&gt;
发送时间: 2022年7月7日 19:23
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JaimeCheng/vue-esign] 你好，更新到1.1.2版本后，生成的方法会报错找不到 ‘format’ (Issue #15)





 
你好，更新到1.1.2版本后，会报错如下：
 Cannot read properties of undefined (reading 'format')
 
但是我看generate()生成图片的方法，里面可以默认不填内容，是不是可以不对图片进行质量压缩？
