### ISSUE TITLE
手写签名偏移过大

### ISSUE THREAD

**Issue by xdw898618984** [JaimeCheng/vue-esign#2]
使用vue-esign 时，手机侧向，第一个字便宜正常，第二个就偏移过大， 使用得是demo实例

**Comment by xdw898618984** [comment]
我是设置了canvas高度100% ，出现了这个问题

**Comment by xdw898618984** [comment]
在执行过程中， 画布一连贯操作，可以写完，断续操作，部分笔画写不上

**Comment by JaimeCheng** [comment]
> 在执行过程中， 画布一连贯操作，可以写完，断续操作，部分笔画写不上

好的，有空我看一下，感谢提出问题！

**Comment by xdw898618984** [comment]
这个问题我已经找到原因了，因为我设置了背景文字，脱离了文档流！导致了断续绘制出现问题





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JaimeCheng ***@***.***&gt;
发送时间: 2021年5月20日 09:30
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: xdw898618984 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JaimeCheng/vue-esign] 手写签名偏移过大 (#2)

**Comment by JaimeCheng** [comment]
> 使用vue-esign 时，手机侧向，第一个字便宜正常，第二个就偏移过大， 使用得是demo实例

那这个呢？

**Comment by xdw898618984** [comment]
这个我是设置了百分比影响了他，目前我也只能设置个定宽，才能不受影响



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JaimeCheng ***@***.***&gt;
发送时间: 2021年5月20日 09:34
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: xdw898618984 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JaimeCheng/vue-esign] 手写签名偏移过大 (#2)





  
使用vue-esign 时，手机侧向，第一个字便宜正常，第二个就偏移过大， 使用得是demo实例
  
那这个呢？

**Comment by JaimeCheng** [comment]
嗯，我最近研究下，感谢！

**Comment by xdw898618984** [comment]
感谢开发插件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JaimeCheng ***@***.***&gt;
发送时间: 2021年5月20日 09:37
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: xdw898618984 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JaimeCheng/vue-esign] 手写签名偏移过大 (#2)





 
嗯，我最近研究下，感谢！

**Comment by xdw898618984** [comment]
我刚刚又踩了一个坑，发现在qq浏览器中，绘制偏移很大，uc没有问题

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JaimeCheng ***@***.***&gt;
发送时间: 2021年5月20日 09:37
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: xdw898618984 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[JaimeCheng/vue-esign] 手写签名偏移过大 (#2)





 
嗯，我最近研究下，感谢！

**Comment by JaimeCheng** [comment]
已更新 支持vue3，已增加属性 控制清空画布时是否清空背景色
