### ISSUE TITLE
安装后运行提示Uncaught (in promise) TypeError: selfHook.bind is not a function

### ISSUE THREAD

**Issue by dvkyle** [JaimeCheng/vue-esign#3]
我在用vue3，网上说可能是不兼容vue3，有大神知道这个问题吗？ 
![image](https://user-images.githubusercontent.com/7709267/120663254-70c84180-c4bc-11eb-91f7-363c3010faac.png)

**Comment by JaimeCheng** [comment]
不兼容




Cheng
***@***.***




------------------ 原始邮件 ------------------
发件人: dvkyle ***@***.***&gt;
发送时间: 2021年6月3日 22:39
收件人: JaimeCheng/vue-esign ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[JaimeCheng/vue-esign] 安装后运行提示Uncaught (in promise) TypeError: selfHook.bind is not a function (#3)





 
我在用vue3，网上说可能是不兼容vue3，有大神知道这个问题吗？

**Comment by JaimeCheng** [comment]
但是有这个计划，以后会兼容vue3

**Comment by JaimeCheng** [comment]
> 我在用vue3，网上说可能是不兼容vue3，有大神知道这个问题吗？ ![image](https://user-images.githubusercontent.com/7709267/120663254-70c84180-c4bc-11eb-91f7-363c3010faac.png)

已更新 支持vue3，已增加属性 控制清空画布时是否清空背景色

**Comment by JaimeCheng** [comment]
已更新 支持vue3，已增加属性 控制清空画布时是否清空背景色
