### ISSUE TITLE
可以回显签名吗？

### ISSUE THREAD

**Issue by PetalsOnaWet** [JaimeCheng/vue-esign#7]
可以回显签名吗？

**Comment by PetalsOnaWet** [comment]
如果之前有签名，回显出来

**Comment by JaimeCheng** [comment]
暂不支持

**Comment by PetalsOnaWet** [comment]
解决了。

` onMounted(() => {
        var image = new Image();
        image.src = '/public/resource/test.jpeg'; //要回显的签名，通常通过后台获取，
        const canvas = document.querySelectorAll('canvas')[0];
        const ctx = canvas.getContext('2d');
        console.log(canvas);
        image.onload = function () {

          //这里宽高变了，用户如果想签名，点击重置后，宽高不会重置，所以需要在重置函数中，重新给canvas赋值宽高
          canvas.width = image.width; 
          canvas.height = image.height;

          ctx.drawImage(image, 0, 0);
        };
      });
//重置时重新赋值宽高
      const handleReset = () => {
        const canvas = document.querySelectorAll('canvas')[0];
        canvas.width = width;
        console.log(height, '44');
        canvas.height = height;
        esign.value.reset();
      };
      `
