### ISSUE TITLE
如果可以支持是否有内容校验就更好了

### ISSUE THREAD

**Issue by llooooooo** [JaimeCheng/vue-esign#8]

**Comment by JaimeCheng** [comment]
不是有判断是否签名了吗 你的内容校验是指什么

**Comment by llooooooo** [comment]
> 不是有判断是否签名了吗 你的内容校验是指什么

我的意思就是判断是否签名，现在有这个支持吗

**Comment by JaimeCheng** [comment]
有的！
![image](https://user-images.githubusercontent.com/22406024/164419345-ae2a060e-e068-48f6-84fd-b582933cbca6.png)
